theme: jekyll-theme-time-machine
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: 
  facebook: WesnerMendozaDS 
  flickr:
  github: /WesnerDaniel
  instagram: wesnerdaniel
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: /WesnerMendozaDS
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
